/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionTree: typeof import('./resources/ts/components/bots/ActionTree.vue')['default']
    AddNodeMenu: typeof import('./resources/ts/components/bots/AddNodeMenu.vue')['default']
    AdminDashboardContent: typeof import('./resources/ts/components/dashboards/AdminDashboardContent.vue')['default']
    Apis: typeof import('./resources/ts/components/settings/apis.vue')['default']
    BaseBreadcrumb: typeof import('./resources/ts/@core/components/BaseBreadcrumb.vue')['default']
    BotBuilderToolbar: typeof import('./resources/ts/components/bots/BotBuilderToolbar.vue')['default']
    BotDialogSlotEditor: typeof import('./resources/ts/components/BotDialogSlotEditor.vue')['default']
    CardHeader: typeof import('./resources/ts/@core/components/CardHeader.vue')['default']
    CardHeaderFooter: typeof import('./resources/ts/@core/components/CardHeaderFooter.vue')['default']
    ComponentTitle: typeof import('./resources/ts/@core/components/ComponentTitle.vue')['default']
    Configuration: typeof import('./resources/ts/components/settings/configuration.vue')['default']
    CustomFunctions: typeof import('./resources/ts/components/settings/custom-functions.vue')['default']
    CustomVariables: typeof import('./resources/ts/components/settings/custom-variables.vue')['default']
    DateRangePicker: typeof import('./resources/ts/components/DateRangePicker.vue')['default']
    DateTimePicker: typeof import('./resources/ts/components/DateTimePicker.vue')['default']
    DialogPickerField: typeof import('./resources/ts/components/DialogPickerField.vue')['default']
    EarningsDonut: typeof import('./resources/ts/components/dashboards/earnings-donut.vue')['default']
    FlowNodeCard: typeof import('./resources/ts/components/bots/FlowNodeCard.vue')['default']
    Hero: typeof import('./resources/ts/components/dashboards/hero.vue')['default']
    InteractiveDialogEditor: typeof import('./resources/ts/components/InteractiveDialogEditor.vue')['default']
    InteractiveOptionsDialog: typeof import('./resources/ts/components/InteractiveOptionsDialog.vue')['default']
    MediaMessage: typeof import('./resources/ts/components/chat/MediaMessage.vue')['default']
    NodeEditor: typeof import('./resources/ts/components/bots/NodeEditor.vue')['default']
    OperatingHoursEditor: typeof import('./resources/ts/components/OperatingHoursEditor.vue')['default']
    PageHeader: typeof import('./resources/ts/components/PageHeader.vue')['default']
    RichTextArea: typeof import('./resources/ts/components/RichTextArea.vue')['default']
    RichTextEditor: typeof import('./resources/ts/components/RichTextEditor.vue')['default']
    RichTextField: typeof import('./resources/ts/components/RichTextField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stat: typeof import('./resources/ts/components/dashboards/stat.vue')['default']
    SvgSprite: typeof import('./resources/ts/@core/components/SvgSprite.vue')['default']
    TagVariableInput: typeof import('./resources/ts/components/TagVariableInput.vue')['default']
    TenantDashboardContent: typeof import('./resources/ts/components/dashboards/TenantDashboardContent.vue')['default']
    TipTapEditor: typeof import('./resources/ts/components/TipTapEditor.vue')['default']
    UiChildCard: typeof import('./resources/ts/@core/components/UiChildCard.vue')['default']
    UiParentCard: typeof import('./resources/ts/@core/components/UiParentCard.vue')['default']
    UiTableCard: typeof import('./resources/ts/@core/components/UiTableCard.vue')['default']
    UiTitleCard: typeof import('./resources/ts/@core/components/UiTitleCard.vue')['default']
    ValidationPanel: typeof import('./resources/ts/components/bots/ValidationPanel.vue')['default']
    WhatsappCard: typeof import('./resources/ts/components/dashboards/whatsapp-card.vue')['default']
    WidgetCard: typeof import('./resources/ts/@core/components/WidgetCard.vue')['default']
  }
}
