/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'account-error': RouteRecordInfo<'account-error', '/account-error', Record<never, never>, Record<never, never>>,
    'bots': RouteRecordInfo<'bots', '/bots', Record<never, never>, Record<never, never>>,
    'bots-bot-id-flowbuilder': RouteRecordInfo<'bots-bot-id-flowbuilder', '/bots/:botId/flowbuilder', { botId: ParamValue<true> }, { botId: ParamValue<false> }>,
    'bots-id': RouteRecordInfo<'bots-id', '/bots/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'bots-id-settings': RouteRecordInfo<'bots-id-settings', '/bots/:id/settings', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'bots-bot-flows': RouteRecordInfo<'bots-bot-flows', '/bots/BotFlows', Record<never, never>, Record<never, never>>,
    'bots-create': RouteRecordInfo<'bots-create', '/bots/create', Record<never, never>, Record<never, never>>,
    'bots-functions': RouteRecordInfo<'bots-functions', '/bots/functions', Record<never, never>, Record<never, never>>,
    'bots-functions-buit-in': RouteRecordInfo<'bots-functions-buit-in', '/bots/functions/buitIn', Record<never, never>, Record<never, never>>,
    'bots-functions-create': RouteRecordInfo<'bots-functions-create', '/bots/functions/create', Record<never, never>, Record<never, never>>,
    'bots-functions-integrations': RouteRecordInfo<'bots-functions-integrations', '/bots/functions/integrations', Record<never, never>, Record<never, never>>,
    'conversations': RouteRecordInfo<'conversations', '/conversations', Record<never, never>, Record<never, never>>,
    'conversations-id': RouteRecordInfo<'conversations-id', '/conversations/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'error500': RouteRecordInfo<'error500', '/error500', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'general': RouteRecordInfo<'general', '/General', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'login-copy': RouteRecordInfo<'login-copy', '/loginCopy', Record<never, never>, Record<never, never>>,
    'logs': RouteRecordInfo<'logs', '/logs', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'notifications': RouteRecordInfo<'notifications', '/notifications', Record<never, never>, Record<never, never>>,
    'paths': RouteRecordInfo<'paths', '/Paths', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    'roles': RouteRecordInfo<'roles', '/roles', Record<never, never>, Record<never, never>>,
    'subscription': RouteRecordInfo<'subscription', '/Subscription', Record<never, never>, Record<never, never>>,
    'templates': RouteRecordInfo<'templates', '/templates', Record<never, never>, Record<never, never>>,
    'tenants': RouteRecordInfo<'tenants', '/tenants', Record<never, never>, Record<never, never>>,
    'tenants-configuration': RouteRecordInfo<'tenants-configuration', '/tenants/configuration', Record<never, never>, Record<never, never>>,
    'tenants-create': RouteRecordInfo<'tenants-create', '/tenants/create', Record<never, never>, Record<never, never>>,
    'text-slider': RouteRecordInfo<'text-slider', '/TextSlider', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
    'users-create': RouteRecordInfo<'users-create', '/users/create', Record<never, never>, Record<never, never>>,
    'users-details': RouteRecordInfo<'users-details', '/users/Details', Record<never, never>, Record<never, never>>,
    'users-details-id': RouteRecordInfo<'users-details-id', '/users/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'users-invite': RouteRecordInfo<'users-invite', '/users/invite', Record<never, never>, Record<never, never>>,
    'users-members': RouteRecordInfo<'users-members', '/users/Members', Record<never, never>, Record<never, never>>,
    'users-profile': RouteRecordInfo<'users-profile', '/users/Profile', Record<never, never>, Record<never, never>>,
    'whatsapp': RouteRecordInfo<'whatsapp', '/whatsapp', Record<never, never>, Record<never, never>>,
    'whatsapp-connect': RouteRecordInfo<'whatsapp-connect', '/whatsapp/connect', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
