import {
  mdiCheckboxMarkedCircleOutline,
  mdiChevronDown,
  mdiChevronUp,
  mdiChevronRight,
  mdiChevronLeft,
  mdiCircle,
  mdiCircleOutline,
  mdiCloseCircle,
  mdiHeart,
  mdiHeartHalf,
  mdiHeartOutline,
  mdiMagnify,
  mdiBriefcase,
  mdiBriefcaseOutline,
  mdiCurrencyUsd,
  mdiTextBox,
  mdiFilePlus,
  mdiPlus,
  mdiDotsVertical,
  mdiDotsHorizontal,
  mdiAccountEye,
  mdiTrashCan,
  mdiTrashCanOutline,
  mdiFileDocumentCheckOutline,
  mdiFileDocumentOutline,
  mdiFileDocument,
  mdiFileDocumentRefresh,
  mdiCalendarOutline,
  mdiMapMarker,
  mdiMapMarkerOutline,
  mdiBookmark,
  mdiBookmarkOutline,
  mdiArrowRight,
  mdiArrowLeft,
  mdiAccountSupervisorOutline,
  mdiAccount,
  mdiAccountOff,
  mdiAccountOutline,
  mdiAccountCircleOutline,
  mdiAccountCogOutline,
  mdiCogOutline,
  mdiCog,
  mdiWeb,
  mdiCloudUploadOutline,
  mdiLinkVariant,
  mdiPlusCircleOutline,
  mdiPencil,
  mdiCalendarMonthOutline,
  mdiAccountSchoolOutline,
  mdiAccountCheck,
  mdiAccountCheckOutline,
  mdiSchool,
  mdiSchoolOutline,
  mdiTrophyAward,
  mdiAccountSupervisor,
  mdiInvoiceSendOutline,
  mdiCheckCircle,
  mdiCheck,
  mdiAlertCircleOutline,
  mdiAlertCircle,
  mdiCloseCircleOutline,
  mdiCheckCircleOutline,
  mdiStarOutline,
  mdiCakeVariantOutline,
  mdiMapOutline,
  mdiClipboardTextOutline,
  mdiLayersTriple,
  mdiLayersTripleOutline,
  mdiPhoneInTalkOutline,
  mdiMapMarkerRadiusOutline,
  mdiEmail,
  mdiEmailOutline,
  mdiSortVariant,
  mdiEyeCircleOutline,
  mdiInformation,
  mdiClockOutline,
  mdiClock,
  mdiPlay,
  mdiPlayOutline,
  mdiSendVariant,
  mdiSendOutline,
  mdiChartBar,
  mdiHelpCircle,
  mdiHelpCircleOutline,
  mdiFormatListBulleted,
  mdiTrayArrowDown,
  mdiTrayArrowUp,
  mdiBrain,
  mdiStar,
  mdiFormatBold,
  mdiFormatItalic,
  mdiFormatUnderline,
  mdiFormatListNumbered,
  mdiFormatStrikethroughVariant,
  mdiCommentTextMultipleOutline,
  mdiChartTimelineVariant,
  mdiChartTimeline,
  mdiDoorOpen,
  mdiCalendarClockOutline,
  mdiCloseOutline,
  mdiClose,
  mdiDomain,
  mdiOfficeBuildingMarker,
  mdiOfficeBuildingMarkerOutline,
  mdiBriefcaseOff,
  mdiBriefcaseOffOutline,
  mdiAccountCog,
  mdiAttachment,
  mdiAccountGroup,
  mdiAccountGroupOutline,
  mdiGavel,
  mdiWheelchairAccessibility,
  mdiHistory,
  mdiHome,
  mdiHomeCity,
  mdiMailbox,
  mdiLogout,
  mdiAccountNetwork,
  mdiAccountNetworkOutline,
  mdiPhoneSettings,
  mdiPhoneSettingsOutline,
  mdiBookOpenVariantOutline,
  mdiBookOpenVariant,
  mdiAccountSchool,
  mdiTextAccount,
  mdiChairSchool,
  mdiAccountVoice,
  mdiCancel,
  mdiReload,
  mdiShield,
  mdiContentSave,
  mdiContentSaveOutline,
  mdiClockAlert,
  mdiClockAlertOutline,
  mdiAccountMultiple,
  mdiAccountMultipleOutline,
  mdiEmoticon,
  mdiEmoticonAngry,
  mdiEmoticonAngryOutline,
  mdiEmoticonExcited,
  mdiEmoticonExcitedOutline,
  mdiEmoticonHappy,
  mdiEmoticonHappyOutline,
  mdiEmoticonNeutral,
  mdiEmoticonNeutralOutline,
  mdiEmoticonSad,
  mdiEmoticonSadOutline,
  mdiHandshake,
  mdiHandshakeOutline,
  mdiThumbUp,
  mdiThumbDown,
  mdiTrendingUp,
  mdiCheckAll,
  mdiAccountTie,
  mdiGift,
  mdiGiftOutline,
  mdiFacebook,
  mdiTwitter,
  mdiInstagram,
  mdiLinkedin,
  mdiFolderOpen,
  mdiFolderOpenOutline,
  mdiSigma,
  mdiSigmaLower,
  mdiCashMultiple,
  mdiBellRingOutline,
  mdiBellRing,
  mdiCalendarBlankOutline,
  mdiFileSign,
  mdiMinus,
  mdiMinusCircle,
  mdiMinusCircleOutline,
  mdiPauseCircleOutline,
  mdiProgressClock,
  mdiCircleMedium,
  mdiFilterVariant,
  mdiFilter,
  mdiFilterOutline,
  mdiFilterMultiple,
  mdiFilterMultipleOutline,
  mdiMagnifyClose,
  mdiTimerAlert,
  mdiOpenInNew,
  mdiAutorenew,
  mdiCloudDownloadOutline,
  mdiCloudDownload,
  mdiTimerSand,
  mdiViewDashboard,
  mdiViewDashboardOutline,
  mdiLightningBolt,
  mdiLightningBoltOutline,
  mdiAccountPlus,
  mdiAccountPlusOutline,
  mdiCreation,
  mdiSwapHorizontal,
  mdiHeadset,
  mdiNumeric1CircleOutline,
  mdiNumeric2CircleOutline,
  mdiNumeric3CircleOutline,
  mdiLockOpenVariant,
  mdiLockOpenVariantOutline,
  mdiLockOutline,
  mdiLock,
  mdiAccountLock,
  mdiImageOutline,
  mdiImageAutoAdjust,
  mdiVideoAccount,
  mdiRocketLaunch,
  mdiRocketLaunchOutline,
  mdiShieldCheck,
  mdiShieldAccount,
  mdiRobotHappy,
  mdiRobotHappyOutline,
  mdiAlarm,
  mdiAlarmBell,
  mdiAccountCircle,
  mdiAccountCreditCard,
  mdiAccountCreditCardOutline,
  mdiCreditCardMarker,
  mdiBank,
  mdiReceiptText,
  mdiCardAccountDetails,
  mdiGenderMaleFemale,
  mdiPassport,
  mdiDelete,
  mdiDeleteForever,
  mdiAccountCash,
  mdiLogin,
  mdiLoginVariant,
  mdiFileExcelOutline,
  mdiFileExcel,
  mdiFilePdfBox,
  mdiLicense,
  mdiMicroscope,
  mdiMonitor,
  mdiServer,
  mdiImageMultiple,
  mdiImageMultipleOutline,
  mdiTreasureChest,
  mdiTreasureChestOutline,
  mdiSitemap,
  mdiSitemapOutline,
  mdiAccountFileText,
  mdiPackageDown,
  mdiPackageUp,
  mdiFileTree,
  mdiClipboardText,
  mdiClipboardOutline,
  mdiViewList,
  mdiOfficeBuilding,
  mdiEye,
  mdiBullseye,
  mdiBullseyeArrow,
  mdiMedal,
  mdiAccountArrowRight,
  mdiAccountStar,
  mdiSubdirectoryArrowRight,
  mdiSubdirectoryArrowLeft,
  mdiChessQueen,
  mdiAccountSwitch,
  mdiMagnifyMinus,
  mdiMagnifyPlus,
  mdiChartBox,
  mdiChartLine,
  mdiStairs,
  mdiFileCode,
  mdiUnfoldMoreHorizontal,
  mdiUnfoldLessHorizontal,
  mdiFlagVariant,
  mdiFlagVariantOutline,
  mdiFlagCheckered,
  mdiMicrosoft,
  mdiTuneVariant,
  mdiTune,
  mdiScaleUnbalanced,
  mdiAutoFix,
  mdiAccountMultiplePlus,
  mdiClipboardCheck,
  mdiArrowDownBold,
  mdiFileDocumentEdit,
  mdiAlert,
  mdiAccountMultipleCheck,
  mdiCompareHorizontal,
  mdiRobot,
  mdiWhatsapp,
  mdiLinkOff,
  mdiCodeJson,
  mdiChat,
  mdiChatOutline,
  mdiArrowDown,
  mdiArrowUp,
  mdiMessageText,
  mdiRadioboxMarked,
  mdiVariable,
  mdiCodeTags,
  mdiApi,
  mdiFunction,
  mdiNavigation,
  mdiNavigationOutline,
  mdiNavigationVariant,
  mdiNavigationVariantOutline,
  mdiXml,
  mdiHumanGreetingProximity,
  mdiPublish,
} from "@mdi/js";

export const icons = {
  checkboxMarkedCircleOutline: mdiCheckboxMarkedCircleOutline,
  circle: mdiCircle,
  circleOutline: mdiCircleOutline,
  closeCircle: mdiCloseCircle,
  chevronUp: mdiChevronUp,
  chevronDown: mdiChevronDown,
  chevronRight: mdiChevronRight,
  chevronLeft: mdiChevronLeft,
  heart: mdiHeart,
  heartOutline: mdiHeartOutline,
  heartHalf: mdiHeartHalf,
  magnify: mdiMagnify,
  briefcase: mdiBriefcase,
  briefcaseOutline: mdiBriefcaseOutline,
  currencyUsd: mdiCurrencyUsd,
  textBox: mdiTextBox,
  filePlus: mdiFilePlus,
  plus: mdiPlus,
  dotsVertical: mdiDotsVertical,
  dotsHorizontal: mdiDotsHorizontal,
  accountEye: mdiAccountEye,
  trashCan: mdiTrashCan,
  trashCanOutline: mdiTrashCanOutline,
  fileDocumentCheckOutline: mdiFileDocumentCheckOutline,
  fileDocumentOutline: mdiFileDocumentOutline,
  fileDocument: mdiFileDocument,
  fileDocumentRefresh: mdiFileDocumentRefresh,
  calendarOutline: mdiCalendarOutline,
  mapMarker: mdiMapMarker,
  mapMarkerOutline: mdiMapMarkerOutline,
  bookMark: mdiBookmark,
  bookMarkOutline: mdiBookmarkOutline,
  arrowRight: mdiArrowRight,
  arrowLeft: mdiArrowLeft,
  accountSupervisorOutline: mdiAccountSupervisorOutline,
  account: mdiAccount,
  accountOff: mdiAccountOff,
  accountOutline: mdiAccountOutline,
  accountCircleOutline: mdiAccountCircleOutline,
  accountCogOutline: mdiAccountCogOutline,
  cogOutline: mdiCogOutline,
  cog: mdiCog,
  web: mdiWeb,
  cloudUploadOutline: mdiCloudUploadOutline,
  linkVariant: mdiLinkVariant,
  plusCircleOutline: mdiPlusCircleOutline,
  pencil: mdiPencil,
  calendarMonthOutline: mdiCalendarMonthOutline,
  accountSchoolOutline: mdiAccountSchoolOutline,
  accountCheck: mdiAccountCheck,
  accountCheckOutline: mdiAccountCheckOutline,
  school: mdiSchool,
  schoolOutline: mdiSchoolOutline,
  trophyAward: mdiTrophyAward,
  accountSupervisor: mdiAccountSupervisor,
  invoiceSendOutline: mdiInvoiceSendOutline,
  checkCircleOutline: mdiCheckCircleOutline,
  alertCircleOutline: mdiAlertCircleOutline,
  alertCircle: mdiAlertCircle,
  closeCircleOutline: mdiCloseCircleOutline,
  checkCircle: mdiCheckCircle,
  check: mdiCheck,
  star: mdiStar,
  starOutline: mdiStarOutline,
  cakeVariantOutline: mdiCakeVariantOutline,
  mapOutline: mdiMapOutline,
  clipboardTextOutline: mdiClipboardTextOutline,
  layers: mdiLayersTriple,
  layersTripleOutline: mdiLayersTripleOutline,
  phoneInTalkOutline: mdiPhoneInTalkOutline,
  mapMarkerRadiusOutline: mdiMapMarkerRadiusOutline,
  email: mdiEmail,
  emailOutline: mdiEmailOutline,
  sortVariant: mdiSortVariant,
  eyeCircleOutline: mdiEyeCircleOutline,
  information: mdiInformation,
  clockOutline: mdiClockOutline,
  clock: mdiClock,
  play: mdiPlay,
  playOutline: mdiPlayOutline,
  sendVariant: mdiSendVariant,
  sendOutline: mdiSendOutline,
  chartBar: mdiChartBar,
  helpCircle: mdiHelpCircle,
  helpCircleOutline: mdiHelpCircleOutline,
  formatListBulleted: mdiFormatListBulleted,
  trayArrowDown: mdiTrayArrowDown,
  trayArrowUp: mdiTrayArrowUp,
  arrowUp: mdiArrowUp,
  arrowDown: mdiArrowDown,
  brain: mdiBrain,
  formatBold: mdiFormatBold,
  formatItalic: mdiFormatItalic,
  formatUnderline: mdiFormatUnderline,
  formatStrikethroughVariant: mdiFormatStrikethroughVariant,
  formatListNumbered: mdiFormatListNumbered,
  commentTextMultipleOutline: mdiCommentTextMultipleOutline,
  chartTimelineVariant: mdiChartTimelineVariant,
  chartTimeline: mdiChartTimeline,
  doorOpen: mdiDoorOpen,
  calendarClockOutline: mdiCalendarClockOutline,
  closeOutline: mdiCloseOutline,
  close: mdiClose,
  domain: mdiDomain,
  officeBuildingMarker: mdiOfficeBuildingMarker,
  officeBuildingMarkerOutline: mdiOfficeBuildingMarkerOutline,
  briefcaseOff: mdiBriefcaseOff,
  briefcaseOffOutline: mdiBriefcaseOffOutline,
  accountCog: mdiAccountCog,
  attachment: mdiAttachment,
  accountGroup: mdiAccountGroup,
  accountGroupOutline: mdiAccountGroupOutline,
  gavel: mdiGavel,
  wheelchairAccessibility: mdiWheelchairAccessibility,
  history: mdiHistory,
  home: mdiHome,
  homeCity: mdiHomeCity,
  mailbox: mdiMailbox,
  logout: mdiLogout,
  accountNetwork: mdiAccountNetwork,
  accountNetworkOutline: mdiAccountNetworkOutline,
  phoneSettings: mdiPhoneSettings,
  phoneSettingsOutline: mdiPhoneSettingsOutline,
  bookOpenVariantOutline: mdiBookOpenVariantOutline,
  bookOpenVariant: mdiBookOpenVariant,
  accountSchool: mdiAccountSchool,
  textAccount: mdiTextAccount,
  chairSchool: mdiChairSchool,
  accountVoice: mdiAccountVoice,
  cancel: mdiCancel,
  reload: mdiReload,
  shield: mdiShield,
  contentSave: mdiContentSave,
  contentSaveOutline: mdiContentSaveOutline,
  clockAlert: mdiClockAlert,
  clockAlertOutline: mdiClockAlertOutline,
  accountMultiple: mdiAccountMultiple,
  accountMultipleOutline: mdiAccountMultipleOutline,
  emoticon: mdiEmoticon,
  emoticonAngry: mdiEmoticonAngry,
  emoticonAngryOutline: mdiEmoticonAngryOutline,
  emoticonExcited: mdiEmoticonExcited,
  emoticonExcitedOutline: mdiEmoticonExcitedOutline,
  emoticonHappy: mdiEmoticonHappy,
  emoticonHappyOutline: mdiEmoticonHappyOutline,
  emoticonNeutral: mdiEmoticonNeutral,
  emoticonNeutralOutline: mdiEmoticonNeutralOutline,
  emoticonSad: mdiEmoticonSad,
  emoticonSadOutline: mdiEmoticonSadOutline,
  handshake: mdiHandshake,
  handshakeOutline: mdiHandshakeOutline,
  thumbUp: mdiThumbUp,
  thumbDown: mdiThumbDown,
  trendingUp: mdiTrendingUp,
  checkAll: mdiCheckAll,
  accountTie: mdiAccountTie,
  gift: mdiGift,
  giftOutline: mdiGiftOutline,
  facebook: mdiFacebook,
  twitter: mdiTwitter,
  instagram: mdiInstagram,
  linkedin: mdiLinkedin,
  folderOpen: mdiFolderOpen,
  folderOpenOutline: mdiFolderOpenOutline,
  sigma: mdiSigma,
  sigmaLower: mdiSigmaLower,
  cashMultiple: mdiCashMultiple,
  bellRingOutline: mdiBellRingOutline,
  bellRing: mdiBellRing,
  calendarBlankOutline: mdiCalendarBlankOutline,
  fileSign: mdiFileSign,
  minus: mdiMinus,
  minusCircle: mdiMinusCircle,
  minusCircleOutline: mdiMinusCircleOutline,
  pauseCircleOutline: mdiPauseCircleOutline,
  progressClock: mdiProgressClock,
  circleMedium: mdiCircleMedium,
  filterVariant: mdiFilterVariant,
  filter: mdiFilter,
  filterOutline: mdiFilterOutline,
  filterMultiple: mdiFilterMultiple,
  filterMultipleOutline: mdiFilterMultipleOutline,
  magnifyClose: mdiMagnifyClose,
  timerAlert: mdiTimerAlert,
  openInNew: mdiOpenInNew,
  autorenew: mdiAutorenew,
  cloudDownloadOutline: mdiCloudDownloadOutline,
  cloudDownload: mdiCloudDownload,
  timerSand: mdiTimerSand,
  viewDashboard: mdiViewDashboard,
  viewDashboardOutline: mdiViewDashboardOutline,
  lightningBolt: mdiLightningBolt,
  lightningBoltOutline: mdiLightningBoltOutline,
  accountPlus: mdiAccountPlus,
  accountPlusOutline: mdiAccountPlusOutline,
  creation: mdiCreation,
  swapHorizontal: mdiSwapHorizontal,
  headset: mdiHeadset,
  numeric1CircleOutline: mdiNumeric1CircleOutline,
  numeric2CircleOutline: mdiNumeric2CircleOutline,
  numeric3CircleOutline: mdiNumeric3CircleOutline,
  lockOpenVariant: mdiLockOpenVariant,
  lockOpenVariantOutline: mdiLockOpenVariantOutline,
  lockOutline: mdiLockOutline,
  lock: mdiLock,
  accountLock: mdiAccountLock,
  imageOutline: mdiImageOutline,
  imageAutoAdjust: mdiImageAutoAdjust,
  videoAccount: mdiVideoAccount,
  rocketLaunch: mdiRocketLaunch,
  rocketLaunchOutline: mdiRocketLaunchOutline,
  shieldCheck: mdiShieldCheck,
  shieldAccount: mdiShieldAccount,
  robot: mdiRobot,
  robotHappy: mdiRobotHappy,
  robotHappyOutline: mdiRobotHappyOutline,
  alarm: mdiAlarm,
  alarmBell: mdiAlarmBell,
  accountCircle: mdiAccountCircle,
  accountCreditCard: mdiAccountCreditCard,
  accountCreditCardOutline: mdiAccountCreditCardOutline,
  creditCardMarker: mdiCreditCardMarker,
  bank: mdiBank,
  receiptText: mdiReceiptText,
  cardAccountDetails: mdiCardAccountDetails,
  genderMaleFemale: mdiGenderMaleFemale,
  passport: mdiPassport,
  delete: mdiDelete,
  deleteForever: mdiDeleteForever,
  accountCash: mdiAccountCash,
  login: mdiLogin,
  loginVariant: mdiLoginVariant,
  fileExcelOutline: mdiFileExcelOutline,
  fileExcel: mdiFileExcel,
  filePdfBox: mdiFilePdfBox,
  license: mdiLicense,
  microscope: mdiMicroscope,
  monitor: mdiMonitor,
  server: mdiServer,
  imageMultiple: mdiImageMultiple,
  imageMultipleOutline: mdiImageMultipleOutline,
  treasureChest: mdiTreasureChest,
  treasureChestOutline: mdiTreasureChestOutline,
  siteMap: mdiSitemap,
  siteMapOutline: mdiSitemapOutline,
  accountFileText: mdiAccountFileText,
  packageDown: mdiPackageDown,
  packageUp: mdiPackageUp,
  fileTree: mdiFileTree,
  clipboardText: mdiClipboardText,
  clipboardOutline: mdiClipboardOutline,
  viewList: mdiViewList,
  officeBuilding: mdiOfficeBuilding,
  eye: mdiEye,
  bullseye: mdiBullseye,
  bullseyeArrow: mdiBullseyeArrow,
  medal: mdiMedal,
  accountArrowRight: mdiAccountArrowRight,
  accountStar: mdiAccountStar,
  subdirectoryArrowRight: mdiSubdirectoryArrowRight,
  subdirectoryArrowLeft: mdiSubdirectoryArrowLeft,
  chessQueen: mdiChessQueen,
  accountSwitch: mdiAccountSwitch,
  magnifyMinus: mdiMagnifyMinus,
  magnifyPlus: mdiMagnifyPlus,
  chartBox: mdiChartBox,
  chartLine: mdiChartLine,
  stairs: mdiStairs,
  fileCode: mdiFileCode,
  unfoldMoreHorizontal: mdiUnfoldMoreHorizontal,
  unfoldLessHorizontal: mdiUnfoldLessHorizontal,
  flagVariant: mdiFlagVariant,
  flagVariantOutline: mdiFlagVariantOutline,
  flagCheckered: mdiFlagCheckered,
  microsoft: mdiMicrosoft,
  tuneVariant: mdiTuneVariant,
  tune: mdiTune,
  scaleUnbalanced: mdiScaleUnbalanced,
  autoFix: mdiAutoFix,
  accountMultiplePlus: mdiAccountMultiplePlus,
  clipboardCheck: mdiClipboardCheck,
  arrowDownBold: mdiArrowDownBold,
  fileDocumentEdit: mdiFileDocumentEdit,
  alert: mdiAlert,
  accountMultipleCheck: mdiAccountMultipleCheck,
  compareHorizontal: mdiCompareHorizontal,
  whatsapp: mdiWhatsapp,
  linkOff: mdiLinkOff,
  codeJson: mdiCodeJson,
  chat: mdiChat,
  chatOutline: mdiChatOutline,
  messageText: mdiMessageText,
  radioboxMarked: mdiRadioboxMarked,
  variable: mdiVariable,
  codeTags: mdiCodeTags,
  api: mdiApi,
  function: mdiFunction,
  xml: mdiXml,
  navigation: mdiNavigation,
  navigationOutline: mdiNavigationOutline,
  navigationVariant: mdiNavigationVariant,
  navigationVariantOutline: mdiNavigationVariantOutline,
  humanGreetingProximity: mdiHumanGreetingProximity,
  publish: mdiPublish,
};
