// Dummy data for the conversation list and the active chat thread.
// Swap this out for real API / WebSocket data later.

export const conversations = [
  {
    id: "john-doe",
    name: "John Doe",
    avatar: "https://i.pravatar.cc/100?img=12",
    online: true,
    preview: "How's going with your property search?",
    time: "4:45 pm",
    unread: false,
  },
  {
    id: "travis-barker",
    name: "Travis Barker",
    avatar: "https://i.pravatar.cc/100?img=33",
    online: true,
    preview: "is typing",
    typing: true,
    time: "5:38 pm",
    unread: false,
  },
  {
    id: "kate-rose",
    name: "Kate Rose",
    avatar: "https://i.pravatar.cc/100?img=45",
    online: false,
    preview: "Looking forward to discussing real estate...",
    time: "5:04 pm",
    unread: false,
  },
  {
    id: "robert-parker",
    name: "Robert Parker",
    avatar: "https://i.pravatar.cc/100?img=14",
    online: true,
    preview: "That's fantastic news about the new listi...",
    time: "4:22 pm",
    unread: true,
  },
  {
    id: "emily-johnson",
    name: "Emily Johnson",
    avatar: "https://i.pravatar.cc/100?img=47",
    online: false,
    preview: "Take a look at my recent real estate post...",
    time: "3:59 pm",
    unread: false,
  },
  {
    id: "sophia-brown",
    name: "Sophia Brown",
    avatar: "https://i.pravatar.cc/100?img=23",
    online: true,
    preview: "Discover amazing properties on my page!",
    time: "3:24 am",
    unread: false,
  },
  {
    id: "frederick-k",
    name: "Frederick K.",
    avatar: "https://i.pravatar.cc/100?img=51",
    online: false,
    preview: "Are you considering pest control options...",
    time: "1:06 pm",
    unread: false,
  },
  {
    id: "alexander-jameson",
    name: "Alexander Jameson",
    avatar: "https://i.pravatar.cc/100?img=8",
    online: true,
    preview: "What day and time works best for you to...",
    time: "12:57 pm",
    unread: false,
  },
  {
    id: "tom-hardy",
    name: "Tom Hardy",
    avatar: "https://i.pravatar.cc/100?img=15",
    online: false,
    preview: "This property has such a unique design vi...",
    time: "12:43 pm",
    unread: false,
  },
  {
    id: "vivienne-marigold",
    name: "Vivienne Marigold",
    avatar: "https://i.pravatar.cc/100?img=29",
    online: true,
    preview: "",
    time: "12:17 pm",
    unread: false,
  },
];

// Active thread: Alexander Jameson, matching the reference screenshot.
export const activeThread = {
  id: "alexander-jameson",
  name: "Alexander Jameson",
  avatar: "https://i.pravatar.cc/100?img=8",
  online: true,
  messages: [
    {
      id: "m1",
      from: "them",
      type: "text",
      text: "I'm a manager that's here to help",
      time: "10:37 am",
    },
    {
      id: "m2",
      from: "them",
      type: "audio",
      duration: "2:19",
      time: "10:41 am",
    },
    {
      id: "m3",
      from: "them",
      type: "property",
      text: "This is a modern townhouse in a quiet neighborhood. It has 3 bedrooms, 2 bathrooms, a spacious kitchen and living room 🏠",
      stats: [
        { label: "Daily Visitors", value: "2,429", icon: "visitors" },
        { label: "Building Age", value: "3Y", icon: "building" },
        { label: "Temperature", value: "28°F", icon: "temperature" },
      ],
      time: "10:19 am",
    },
    {
      id: "m4",
      from: "them",
      type: "gallery",
      caption: "Here are the photos:",
      photos: [
        "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=300&h=220&fit=crop",
        "https://images.unsplash.com/photo-1556912167-f556f1f39fdf?w=300&h=220&fit=crop",
        "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=300&h=220&fit=crop",
      ],
      morePhotosCount: 3,
      time: "3:19 pm",
    },
    {
      id: "m5",
      from: "me",
      type: "text",
      text: "Looks good 👍. I want to sign up for a viewing",
      time: "12:25 pm",
    },
    {
      id: "m6",
      from: "them",
      type: "text",
      text: "What day and time works best for you to come by for the viewing? Let me know, and I'll confirm the appointment right away.",
      time: "12:57 pm",
    },
  ],
};
